name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Code quality checks
      run: |
        echo "Running code formatting check..."
        autopep8 --diff --recursive --aggressive --aggressive . --exclude=.git,__pycache__,.pytest_cache,.vscode
        
        echo "Running flake8 linting..."
        flake8 . --exclude=.git,__pycache__,.pytest_cache,.vscode --statistics
    
    - name: Install Firefox for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox-esr
    
    - name: Run tests
      env:
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
        SKIP_BROWSER_TESTS: "true"  # Skip browser tests in CI by default
        PYTHONPATH: app
      run: |
        echo "Running API tests..."
        python -m pytest qa/tests/test_api.py -v
        
        echo "Running browser tests (if enabled)..."
        python -m pytest qa/tests/test_browser.py -v || echo "Browser tests skipped or failed"
