name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache geckodriver
      uses: actions/cache@v3
      with:
        path: ~/.wdm
        key: ${{ runner.os }}-geckodriver-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-geckodriver-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Firefox for browser tests
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
    
    - name: Run full QA pipeline with browser tests
      run: |
        chmod +x ci.sh
        SKIP_BROWSER_TESTS=false ./ci.sh
      env:
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
