name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Code quality checks
      run: |
        echo "Running code formatting check..."
        autopep8 --diff --recursive --aggressive --aggressive . --exclude=.git,__pycache__,.pytest_cache,.vscode
        
        echo "Running flake8 linting..."
        flake8 . --exclude=.git,__pycache__,.pytest_cache,.vscode --statistics
    
    - name: Install Firefox for Selenium (optional)
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        # Install geckodriver
        wget -q https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xzf geckodriver-v0.33.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
      continue-on-error: true
    
    - name: Run API tests
      env:
        SKIP_BROWSER_TESTS: "true"
        PYTHONPATH: ${{ github.workspace }}/app
      run: |
        echo "Running API tests..."
        python -m pytest qa/tests/test_api.py -v
    
    - name: Run browser tests (if enabled)
      env:
        SKIP_BROWSER_TESTS: "true"
        PYTHONPATH: ${{ github.workspace }}/app
      run: |
        echo "Running browser tests (skipped in CI)..."
        python -m pytest qa/tests/test_browser.py -v || echo "Browser tests skipped"
      continue-on-error: true
